#!/bin/bash

if [[ $1 =~ ^[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]+$  ]]; 
then
	echo "imię"
  
elif [[ "$1" =~ ^[0-9]{2}-[0-9]{3}$ ]]; 
then
	echo "kod pocztowy"
  
elif [[ "$1" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; 
then
	echo "email"
  
else
	echo "Nie spełniasz wytycznych"
fi
